import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { SidebarProvider, SidebarInset, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "@/components/app-sidebar";
import Head from "next/head";
import Link from "next/link";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "UangIN",
  description: "Generated by create next app",
  manifest: "/manifest.webmanifest",
  themeColor: "#000000"
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" type="image/png" href="%PUBLIC_URL%/favicon-96x96.png" sizes="96x96" />
        <link rel="icon" type="image/svg+xml" href="%PUBLIC_URL%/favicon.svg" />
        <link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="%PUBLIC_URL%/apple-touch-icon.png" />
        <meta name="apple-mobile-web-app-title" content="UangIN" />
        <link rel="manifest" href="%PUBLIC_URL%/site.webmanifest" />
      </Head>
      <body
        className={`${poppins.variable} font-sans antialiased bg-linear-to-r from-gray-950 via-purple-950 to-gray-950`}
      >
        <SidebarProvider>
          <TooltipProvider>
            <AppSidebar />
            <SidebarInset>
              <SidebarTrigger className="fixed top-2 z-50 left-4 bg-foreground rounded-md shadow-sm"/>
              {children}
            </SidebarInset>
          </TooltipProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
